const fs = require('fs');
const path = require('path');

// Diccionario de significados en español - HSK 1-4 completo
const SIGNIFICADOS = {
  // HSK 1 (300 palabras)
  '爱ài': 'Amar / Amor',
  '吧ba': 'Partícula sugestiva',
  '八bā': 'Ocho',
  '爸爸bàba': 'Papá',
  '百bǎi': 'Cien',
  '白天báitiān': 'Día',
  '半bàn': 'Mitad / Medio',
  '包子bāozi': 'Bollo relleno al vapor',
  '杯子bēizi': 'Taza / Vaso',
  '本běn': 'Clasificador (libros)',
  '本1běn': 'Clasificador (libros)',
  '边biān': 'Lado / Borde',
  '病bìng': 'Enfermedad / Enfermo',
  '不bù': 'No',
  '不客气búkèqi': 'De nada',
  '不要búyào': 'No querer',
  '菜cài': 'Verdura / Comida',
  '茶chá': 'Té',
  '唱chàng': 'Cantar',
  '超市chāoshì': 'Supermercado',
  '车chē': 'Coche / Vehículo',
  '吃chī': 'Comer',
  '穿chuān': 'Llevar puesto / Vestir',
  '出租车chūzūchē': 'Taxi',
  '大dà': 'Grande',
  '打电话dǎdiànhuà': 'Llamar por teléfono',
  '大家dàjiā': 'Todos',
  '到dào': 'Llegar',
  '大学dàxué': 'Universidad',
  '大学生dàxuéshēng': 'Estudiante universitario',
  '的de': 'Partícula posesiva',
  '第dì': 'Prefijo ordinal',
  '店diàn': 'Tienda',
  '点diǎn': 'Punto / Hora',
  '电话diànhuà': 'Teléfono',
  '电脑diànnǎo': 'Computadora',
  '电视diànshì': 'Televisión',
  '电影diànyǐng': 'Película',
  '电影院diànyǐngyuàn': 'Cine',
  '弟弟dìdi': 'Hermano menor',
  '东西dōngxi': 'Cosa',
  '都dōu': 'Todo / Todos',
  '读dú': 'Leer',
  '对duì': 'Correcto',
  '对不起duìbuqǐ': 'Lo siento',
  '多duō': 'Mucho',
  '多少duōshao': 'Cuánto',
  '读书dúshū': 'Leer / Estudiar',
  '二èr': 'Dos',
  '儿子érzi': 'Hijo',
  '饭fàn': 'Comida / Arroz',
  '饭店fàndiàn': 'Restaurante',
  '房间fángjiān': 'Habitación',
  '非常fēicháng': 'Muy',
  '飞机fēijī': 'Avión',
  '分fēn': 'Minuto / Dividir',
  '分钟fēnzhōng': 'Minuto',
  '高兴gāoxìng': 'Contento',
  '个gè': 'Clasificador general',
  '歌gē': 'Canción',
  '哥哥gēge': 'Hermano mayor',
  '给gěi': 'Dar',
  '公司gōngsī': 'Empresa',
  '工作gōngzuò': 'Trabajo / Trabajar',
  '狗gǒu': 'Perro',
  '贵guì': 'Caro',
  '国guó': 'País',
  '还hái': 'Todavía / Aún',
  '孩子háizi': 'Niño',
  '汉语Hànyǔ': 'Chino (idioma)',
  '汉字Hànzì': 'Caracter chino',
  '号hào': 'Número / Día del mes',
  '好hǎo': 'Bueno',
  '好吃hǎochī': 'Delicioso',
  '好看hǎokàn': 'Bonito',
  '好听hǎotīng': 'Agradable de oír',
  '好玩儿hǎowánr': 'Divertido',
  '和hé': 'Y / Con',
  '和1hé': 'Y / Con',
  '喝hē': 'Beber',
  '很hěn': 'Muy',
  '后hòu': 'Después / Detrás',
  '回huí': 'Regresar',
  '会huì': 'Saber hacer / Poder',
  '火车huǒchē': 'Tren',
  '几jǐ': 'Cuántos / Algunos',
  '家jiā': 'Casa / Familia',
  '见jiàn': 'Ver',
  '件jiàn': 'Clasificador (ropa)',
  '叫jiào': 'Llamarse',
  '饺子jiǎozi': 'Empanadilla china',
  '家人jiārén': 'Familia',
  '鸡蛋jīdàn': 'Huevo',
  '姐姐jiějie': 'Hermana mayor',
  '今年jīnnián': 'Este año',
  '今天jīntiān': 'Hoy',
  '九jiǔ': 'Nueve',
  '觉得juéde': 'Sentir / Pensar',
  '开kāi': 'Abrir',
  '开车kāichē': 'Conducir',
  '看kàn': 'Ver / Mirar',
  '看病kànbìng': 'Ver al médico',
  '看见kànjiàn': 'Ver',
  '课kè': 'Clase',
  '可以kěyǐ': 'Poder',
  '口kǒu': 'Boca',
  '块kuài': 'Yuan (moneda)',
  '来lái': 'Venir',
  '老师lǎoshī': 'Profesor',
  '了le': 'Partícula (aspecto)',
  '冷lěng': 'Frío',
  '里lǐ': 'Dentro',
  '两liǎng': 'Dos (medida)',
  '零líng': 'Cero',
  '六liù': 'Seis',
  '吗ma': 'Partícula interrogativa',
  '卖mài': 'Vender',
  '买mǎi': 'Comprar',
  '妈妈māma': 'Mamá',
  '忙máng': 'Ocupado',
  '猫māo': 'Gato',
  '没关系méiguānxi': 'No importa',
  '妹妹mèimei': 'Hermana menor',
  '没事méishì': 'No pasa nada',
  '没（有）méi(yǒu)': 'No tener',
  '们men': 'Sufijo plural',
  '面包miànbāo': 'Pan',
  '面条儿miàntiáor': 'Fideos',
  '米饭mǐfàn': 'Arroz cocido',
  '明年míngnián': 'Año próximo',
  '明天míngtiān': 'Mañana',
  '名字míngzi': 'Nombre',
  '那nà': 'Ese / Eso',
  '哪nǎ': 'Cuál',
  '那边nàbiān': 'Allí',
  '那个nàge': 'Ese',
  '哪个nǎge': 'Cuál',
  '那里nàlǐ': 'Allí',
  '哪里nǎlǐ': 'Dónde',
  '男nán': 'Masculino',
  '男朋友nánpéngyou': 'Novio',
  '那儿nàr': 'Allí',
  '哪儿nǎr': 'Dónde',
  '那些nàxiē': 'Esos',
  '哪些nǎxiē': 'Cuáles',
  '呢ne': 'Partícula interrogativa',
  '能néng': 'Poder',
  '你nǐ': 'Tú',
  '你好nǐhǎo': 'Hola',
  '年nián': 'Año',
  '你们nǐmen': 'Ustedes',
  '您nín': 'Usted (formal)',
  '牛奶niúnǎi': 'Leche',
  '女nǚ': 'Femenino',
  '女儿nǚér': 'Hija',
  '女儿nǚ\'ér': 'Hija',
  '女朋友nǚpéngyou': 'Novia',
  '女士nǚshì': 'Señora',
  '朋友péngyou': 'Amigo',
  '便宜piányi': 'Barato',
  '漂亮piàoliang': 'Bonito',
  '苹果píngguǒ': 'Manzana',
  '七qī': 'Siete',
  '前qián': 'Delante / Antes',
  '钱qián': 'Dinero',
  '千qiān': 'Mil',
  '起床qǐchuáng': 'Levantarse',
  '请qǐng': 'Por favor',
  '请问qǐngwèn': 'Disculpe (pregunta)',
  '去qù': 'Ir',
  '去年qùnián': 'Año pasado',
  '热rè': 'Caliente / Calor',
  '人rén': 'Persona',
  '认识rènshi': 'Conocer',
  '日rì': 'Día / Sol',
  '三sān': 'Tres',
  '上shàng': 'Arriba / Subir',
  '上班shàngbān': 'Ir al trabajo',
  '商店shāngdiàn': 'Tienda',
  '上课shàngkè': 'Ir a clase',
  '上午shàngwǔ': 'Mañana (AM)',
  '上学shàngxué': 'Ir a la escuela',
  '少shǎo': 'Poco',
  '谁shéi/shuí': 'Quién',
  '生病shēngbìng': 'Estar enfermo',
  '什么shénme': 'Qué',
  '十shí': 'Diez',
  '事shì': 'Asunto',
  '是shì': 'Ser / Estar',
  '时候shíhou': 'Momento',
  '时间shíjiān': 'Tiempo',
  '手机shǒujī': 'Teléfono móvil',
  '书shū': 'Libro',
  '书店shūdiàn': 'Librería',
  '睡shuì': 'Dormir',
  '水shuǐ': 'Agua',
  '水果shuǐguǒ': 'Fruta',
  '睡觉shuìjiào': 'Dormir',
  '说shuō': 'Decir / Hablar',
  '说话shuōhuà': 'Hablar',
  '四sì': 'Cuatro',
  '岁suì': 'Años de edad',
  '他tā': 'Él',
  '它tā': 'Ello',
  '她tā': 'Ella',
  '太tài': 'Demasiado',
  '他们tāmen': 'Ellos',
  '它们tāmen': 'Ellos (cosas)',
  '她们tāmen': 'Ellas',
  '天tiān': 'Día / Cielo',
  '天气tiānqì': 'Clima',
  '听tīng': 'Escuchar',
  '听见tīngjiàn': 'Oír',
  '同学tóngxué': 'Compañero de clase',
  '外wài': 'Fuera',
  '外边wàibian': 'Afuera',
  '玩wán': 'Jugar',
  '晚wǎn': 'Tarde',
  '晚饭wǎnfàn': 'Cena',
  '晚上wǎnshang': 'Noche',
  '喂wèi': 'Hola (teléfono)',
  '问wèn': 'Preguntar',
  '问题wèntí': 'Problema / Pregunta',
  '我wǒ': 'Yo',
  '我们wǒmen': 'Nosotros',
  '五wǔ': 'Cinco',
  '午饭wǔfàn': 'Almuerzo',
  '下xià': 'Abajo / Bajar',
  '下雨xiàyǔ': 'Llover',
  '下班xiàbān': 'Salir del trabajo',
  '下课xiàkè': 'Terminar clase',
  '想xiǎng': 'Pensar / Querer',
  '先生xiānsheng': 'Señor',
  '现在xiànzài': 'Ahora',
  '小xiǎo': 'Pequeño',
  '小朋友xiǎopéngyǒu': 'Niño',
  '小时xiǎoshí': 'Hora',
  '小学xiǎoxué': 'Escuela primaria',
  '小学生xiǎoxuéshēng': 'Estudiante de primaria',
  '下午xiàwǔ': 'Tarde (PM)',
  '写xiě': 'Escribir',
  '些xiē': 'Algunos',
  '谢谢xièxie': 'Gracias',
  '喜欢xǐhuan': 'Gustar',
  '新xīn': 'Nuevo',
  '星期xīngqī': 'Semana',
  '星期日xīngqīrì': 'Domingo',
  '星期天xīngqītiān': 'Domingo',
  '休息xiūxi': 'Descansar',
  '学xué': 'Estudiar / Aprender',
  '雪xuě': 'Nieve',
  '学生xuéshēng': 'Estudiante',
  '学习xuéxí': 'Estudiar',
  '学校xuéxiào': 'Escuela',
  '要yào': 'Querer / Necesitar',
  '也yě': 'También',
  '一yī': 'Uno',
  '一半yíbàn': 'Mitad',
  '一点儿yìdiǎnr': 'Un poco',
  '衣服yīfu': 'Ropa',
  '医生yīshēng': 'Médico',
  '一下yíxià': 'Un momento',
  '一些yìxiē': 'Algunos',
  '医院yīyuàn': 'Hospital',
  '椅子yǐzi': 'Silla',
  '有yǒu': 'Tener / Haber',
  '有的yǒude': 'Algunos',
  '有些yǒuxiē': 'Algunos',
  '有（一）点儿yǒu(yì)diǎnr': 'Un poco',
  '雨yǔ': 'Lluvia',
  '元yuán': 'Yuan (moneda)',
  '月yuè': 'Mes / Luna',
  '再zài': 'Otra vez',
  '在zài': 'Estar en',
  '再见zàijiàn': 'Adiós',
  '早zǎo': 'Temprano',
  '早饭zǎofàn': 'Desayuno',
  '早上zǎoshang': 'Mañana temprano',
  '怎么zěnme': 'Cómo',
  '怎么样zěnmeyàng': 'Qué tal',
  '找zhǎo': 'Buscar',
  '这zhè': 'Este / Esto',
  '这边zhèbiān': 'Aquí',
  '这个zhège': 'Este',
  '这里zhèlǐ': 'Aquí',
  '真zhēn': 'Realmente',
  '正在zhèngzài': 'Estar haciendo',
  '这儿zhèr': 'Aquí',
  '这些zhèxiē': 'Estos',
  '只zhī': 'Clasificador (animales)',
  '知道zhīdào': 'Saber',
  '中国Zhōngguó': 'China',
  '中文Zhōngwén': 'Chino (idioma)',
  '中午zhōngwǔ': 'Mediodía',
  '中学zhōngxué': 'Escuela secundaria',
  '中学生zhōngxuéshēng': 'Estudiante secundaria',
  '住zhù': 'Vivir',
  '桌子zhuōzi': 'Mesa',
  '字zì': 'Carácter / Palabra',
  '坐zuò': 'Sentarse',
  '做zuò': 'Hacer',
  '做饭zuòfàn': 'Cocinar',
  '昨天zuótiān': 'Ayer',

  // HSK 2 (200 palabras)
  '啊a': 'Partícula (sorpresa)',
  '爱好àihào': 'Afición',
  '白色báisè': 'Color blanco',
  '班bān': 'Clase / Turno',
  '帮bāng': 'Ayudar',
  '帮忙bāngmáng': 'Ayudar',
  '包bāo': 'Paquete / Bolsa',
  '本子běnzi': 'Cuaderno',
  '比bǐ': 'Comparar',
  '笔bǐ': 'Bolígrafo',
  '别bié': 'No (imperativo)',
  '不好意思bùhǎoyìsi': 'Apenado',
  '不错búcuò': 'No está mal',
  '长cháng': 'Largo',
  '车站chēzhàn': 'Estación',
  '出chū': 'Salir',
  '床chuáng': 'Cama',
  '出国chūguó': 'Salir del país',
  '出来chūlái': 'Salir',
  '出门chūmén': 'Salir de casa',
  '出去chūqù': 'Salir',
  '词cí': 'Palabra',
  '次cì': 'Vez',
  '从cóng': 'Desde',
  '从小cóngxiǎo': 'Desde pequeño',
  '错cuò': 'Equivocado',
  '打dǎ': 'Golpear',
  '打车dǎchē': 'Tomar taxi',
  '打开dǎkāi': 'Abrir',
  '但dàn': 'Pero',
  '但是dànshì': 'Pero',
  '得de': 'Partícula (resultado)',
  '地de': 'Partícula (adverbial)',
  '等děng': 'Esperar',
  '点diǎn': 'Tocar',
  '地铁dìtiě': 'Metro',
  '动dòng': 'Mover',
  '懂dǒng': 'Entender',
  '饭馆fànguǎn': 'Restaurante',
  '飞fēi': 'Volar',
  '高gāo': 'Alto',
  '告诉gàosu': 'Decir / Contar',
  '高中gāozhōng': 'Preparatoria',
  '跟gēn': 'Con',
  '个子gèzi': 'Estatura',
  '公交车gōngjiāochē': 'Autobús',
  '过guo': 'Partícula (experiencia)',
  '过guò': 'Pasar',
  '过来guòlái': 'Venir',
  '过年guònián': 'Año Nuevo',
  '过去guòqù': 'Pasar',
  '还是háishi': 'O',
  '黑色hēisè': 'Color negro',
  '红茶hóngchá': 'Té negro',
  '红色hóngsè': 'Color rojo',
  '后面hòumiàn': 'Detrás',
  '画huà': 'Pintar / Dibujo',
  '花huā': 'Gastar',
  '花huā': 'Flor',
  '坏huài': 'Roto / Malo',
  '回来huílái': 'Regresar',
  '回去huíqù': 'Regresar',
  '间jiān': 'Clasificador (habitación)',
  '教jiāo': 'Enseñar',
  '教室jiàoshì': 'Aula',
  '机场jīchǎng': 'Aeropuerto',
  '记得jìde': 'Recordar',
  '介绍jièshào': 'Presentar',
  '进jìn': 'Entrar',
  '近jìn': 'Cerca',
  '经常jīngcháng': 'A menudo',
  '进来jìnlái': 'Entrar',
  '进去jìnqù': 'Entrar',
  '机票jīpiào': 'Boleto de avión',
  '就jiù': 'Entonces / Ya',
  '酒店jiǔdiàn': 'Hotel',
  '咖啡kāfēi': 'Café',
  '开始kāishǐ': 'Comenzar',
  '开学kāixué': 'Iniciar clases',
  '考kǎo': 'Examinar',
  '考试kǎoshì': 'Examen',
  '可能kěnéng': 'Posible',
  '快kuài': 'Rápido',
  '快乐kuàilè': 'Feliz',
  '快要kuàiyào': 'Pronto',
  '裤子kùzi': 'Pantalones',
  '篮球lánqiú': 'Baloncesto',
  '累lèi': 'Cansado',
  '离lí': 'Distancia',
  '里面lǐmiàn': 'Dentro',
  '楼lóu': 'Edificio',
  '路lù': 'Camino',
  '绿茶lǜchá': 'Té verde',
  '绿色lǜsè': 'Color verde',
  '路上lùshang': 'En el camino',
  '旅游lǚyóu': 'Viajar',
  '慢màn': 'Lento',
  '每měi': 'Cada',
  '没意思méiyìsi': 'Aburrido',
  '门mén': 'Puerta',
  '门口ménkǒu': 'Entrada',
  '门票ménpiào': 'Entrada (boleto)',
  '面miàn': 'Lado',
  '名míng': 'Nombre',
  '拿ná': 'Tomar',
  '奶茶nǎichá': 'Té con leche',
  '奶奶nǎinai': 'Abuela paterna',
  '那么nàme': 'Tan',
  '男孩儿nánháir': 'Niño (chico)',
  '那样nàyàng': 'Así',
  '鸟niǎo': 'Pájaro',
  '女孩儿nǚháir': 'Niña (chica)',
  '旁边pángbiān': 'Al lado',
  '跑pǎo': 'Correr',
  '跑步pǎobù': 'Correr',
  '票piào': 'Boleto',
  '前面qiánmiàn': 'Delante',
  '起来qǐlái': 'Levantarse',
  '晴qíng': 'Despejado',
  '球qiú': 'Pelota',
  '妻子qīzi': 'Esposa',
  '让ràng': 'Dejar / Permitir',
  '肉ròu': 'Carne',
  '商场shāngchǎng': 'Centro comercial',
  '上来shànglái': 'Subir',
  '上面shàngmiàn': 'Arriba',
  '上去shàngqù': 'Subir',
  '上网shàngwǎng': 'Navegar internet',
  '生日shēngrì': 'Cumpleaños',
  '身体shēntǐ': 'Cuerpo',
  '时shí': 'Tiempo',
  '事情shìqing': 'Asunto',
  '手shǒu': 'Mano',
  '手表shǒubiǎo': 'Reloj de mano',
  '书包shūbāo': 'Mochila',
  '舒服shūfu': 'Cómodo',
  '送sòng': 'Enviar',
  '虽然suīrán': 'Aunque',
  '所以suǒyǐ': 'Por eso',
  '疼téng': 'Doler',
  '题tí': 'Pregunta',
  '踢tī': 'Patear',
  '条tiáo': 'Clasificador (largo)',
  '跳舞tiàowǔ': 'Bailar',
  '头tóu': 'Cabeza',
  '外国wàiguó': 'País extranjero',
  '外面wàimiàn': 'Afuera',
  '完wán': 'Terminar',
  '万wàn': 'Diez mil',
  '忘wàng': 'Olvidar',
  '往wǎng': 'Hacia',
  '网上wǎngshang': 'En internet',
  '位wèi': 'Clasificador (persona)',
  '为什么wèishénme': 'Por qué',
  '洗xǐ': 'Lavar',
  '下来xiàlái': 'Bajar',
  '下面xiàmiàn': 'Abajo',
  '笑xiào': 'Reír',
  '小孩儿xiǎoháir': 'Niño',
  '小时候xiǎoshíhou': 'Infancia',
  '下去xiàqù': 'Bajar',
  '姓xìng': 'Apellido',
  '姓名xìngmíng': 'Nombre completo',
  '洗手间xǐshǒujiān': 'Baño',
  '希望xīwàng': 'Esperar',
  '眼睛yǎnjing': 'Ojo',
  '颜色yánsè': 'Color',
  '药yào': 'Medicina',
  '药店yàodiàn': 'Farmacia',
  '爷爷yéye': 'Abuelo paterno',
  '一会儿yíhuìr': 'Un momento',
  '已经yǐjīng': 'Ya',
  '阴yīn': 'Nublado',
  '因为yīnwèi': 'Porque',
  '一起yìqǐ': 'Juntos',
  '意思yìsi': 'Significado',
  '游yóu': 'Nadar',
  '右yòu': 'Derecha',
  '有意思yǒuyìsi': 'Interesante',
  '右边yòubian': 'Lado derecho',
  '有时（候）yǒushí(hou)': 'A veces',
  '游泳yóuyǒng': 'Nadar',
  '鱼yú': 'Pescado',
  '远yuǎn': 'Lejos',
  '运动yùndòng': 'Deporte',
  '站zhàn': 'Estación / Parada',
  '丈夫zhàngfu': 'Esposo',
  '着zhe': 'Partícula (duración)',
  '这么zhème': 'Tan',
  '正zhèng': 'Justo',
  '这样zhèyàng': 'Así',
  '周zhōu': 'Semana',
  '准备zhǔnbèi': 'Preparar',
  '自己zìjǐ': 'Mismo / Uno mismo',
  '走zǒu': 'Caminar',
  '走路zǒulù': 'Caminar',
  '最zuì': 'Más (superlativo)',
  '左zuǒ': 'Izquierda',
  '左边zuǒbian': 'Lado izquierdo',
  '足球zúqiú': 'Fútbol',

  // HSK 3 (500 palabras) - Parte 1
  '矮ǎi': 'Bajo (altura)',
  '爱人àiren': 'Cónyuge',
  '安静ānjìng': 'Tranquilo',
  '安全ānquán': 'Seguro',
  '阿姨āyí': 'Tía',
  '把bǎ': 'Preposición objeto',
  '办bàn': 'Hacer / Gestionar',
  '搬bān': 'Mudarse',
  '办法bànfǎ': 'Método',
  '办公室bàngōngshì': 'Oficina',
  '帮助bāngzhù': 'Ayudar',
  '班级bānjí': 'Clase (grupo)',
  '搬家bānjiā': 'Mudarse de casa',
  '半天bàntiān': 'Medio día',
  '饱bǎo': 'Lleno (comida)',
  '报纸bàozhǐ': 'Periódico',
  '被bèi': 'Preposición pasiva',
  '北běi': 'Norte',
  '北方běifāng': 'Norte',
  '变biàn': 'Cambiar',
  '遍biàn': 'Vez (completa)',
  '变成biànchéng': 'Convertirse en',
  '变化biànhuà': 'Cambio',
  '表演biǎoyǎn': 'Actuar',
  '别的biéde': 'Otro',
  '别人biérén': 'Otra persona',
  '笔记bǐjì': 'Apuntes',
  '比较bǐjiào': 'Comparar',
  '笔记本bǐjìběn': 'Cuaderno',
  '冰bīng': 'Hielo',
  '冰激凌bīngjīlíng': 'Helado',
  '病人bìngrén': 'Paciente',
  '宾馆bīnguǎn': 'Hotel',
  '冰箱bīngxiāng': 'Refrigerador',
  '比如bǐrú': 'Por ejemplo',
  '比赛bǐsài': 'Competencia',
  '必须bìxū': 'Deber',
  '不同bùtóng': 'Diferente',
  '不但búdàn': 'No solo',
  '不见bújiàn': 'No ver',
  '不久bùjiǔ': 'Pronto',
  '不行bùxíng': 'No funciona',
  '不用búyòng': 'No necesitar',
  '才cái': 'Apenas / Solo',
  '菜单càidān': 'Menú',
  '参加cānjiā': 'Participar',
  '草cǎo': 'Hierba',
  '草地cǎodì': 'Césped',
  '层céng': 'Piso',
  '查chá': 'Buscar',
  '差chà': 'Diferencia',
  '差不多chàbuduō': 'Casi',
  '尝cháng': 'Probar (comida)',
  '常cháng': 'Frecuente',
  '常见chángjiàn': 'Común',
  '常用chángyòng': 'De uso común',
  '常常chángcháng': 'A menudo',
  '成绩chéngjì': 'Calificación',
  '城市chéngshì': 'Ciudad',
  '衬衫chènshān': 'Camisa',
  '迟到chídào': 'Llegar tarde',
  '船chuán': 'Barco',
  '出发chūfā': 'Partir',
  '除了chúle': 'Excepto',
  '春天chūntiān': 'Primavera',
  '出生chūshēng': 'Nacer',
  '出院chūyuàn': 'Salir del hospital',
  '初中chūzhōng': 'Secundaria',
  '词典cídiǎn': 'Diccionario',
  '聪明cōngmíng': 'Inteligente',
  '大概dàgài': 'Aproximadamente',
  '带dài': 'Llevar',
  '蛋糕dàngāo': 'Pastel',
  '当然dāngrán': 'Por supuesto',
  '担心dānxīn': 'Preocuparse',
  '到处dàochù': 'Por todas partes',
  '大人dàren': 'Adulto',
  '打扫dǎsǎo': 'Limpiar',
  '打算dǎsuàn': 'Planear',
  '大小dàxiǎo': 'Tamaño',
  '大熊猫dàxióngmāo': 'Panda gigante',
  '大衣dàyī': 'Abrigo',
  '得dé': 'Obtener',
  '得到dédào': 'Obtener',
  '得分défēn': 'Anotar puntos',
  '的话dehuà': 'Si (condicional)',
  '得děi': 'Deber',
  '灯dēng': 'Lámpara',
  '地dì': 'Tierra',
  '电diàn': 'Electricidad',
  '电梯diàntī': 'Elevador',
  '电子书diànzǐshū': 'Libro electrónico',
  '地点dìdiǎn': 'Lugar',
  '地方dìfang': 'Lugar',
  '地图dìtú': 'Mapa',
  '丢diū': 'Perder',
  '东dōng': 'Este',
  '东北dōngběi': 'Noreste',
  '懂得dǒngde': 'Comprender',
  '东方dōngfāng': 'Este / Oriente',
  '东南dōngnán': 'Sureste',
  '冬天dōngtiān': 'Invierno',
  '动物dòngwù': 'Animal',
  '动物园dòngwùyuán': 'Zoológico',
  '段duàn': 'Sección',
  '短duǎn': 'Corto',
  '短裤duǎnkù': 'Shorts',
  '锻炼duànliàn': 'Ejercitar',
  '对话duìhuà': 'Diálogo',
  '饿è': 'Hambriento',
  '耳朵ěrduo': 'Oreja',
  '耳机ěrjī': 'Auriculares',
  '而且érqiě': 'Además',
  '发fā': 'Enviar',
  '放fàng': 'Poner',
  '方便fāngbiàn': 'Conveniente',
  '方便面fāngbiànmiàn': 'Fideos instantáneos',
  '方法fāngfǎ': 'Método',
  '放假fàngjià': 'Vacaciones',
  '方向fāngxiàng': 'Dirección',
  '放心fàngxīn': 'Tranquilizarse',
  '放学fàngxué': 'Salir de clase',
  '房子fángzi': 'Casa',
  '发烧fāshāo': 'Tener fiebre',
  '发生fāshēng': 'Ocurrir',
  '发现fāxiàn': 'Descubrir',
  '发展fāzhǎn': 'Desarrollar',
  '风fēng': 'Viento',
  '封fēng': 'Clasificador (carta)',
  '分开fēnkāi': 'Separar',
  '附近fùjìn': 'Cerca',
  '夫妻fūqī': 'Pareja casada',
  '服务fúwù': 'Servicio',
  '复习fùxí': 'Repasar',
  '该gāi': 'Deber',
  '干gàn': 'Hacer',
  '感兴趣gǎnxìngqù': 'Interesarse',
  '感到gǎndào': 'Sentir',
  '刚gāng': 'Recién',
  '刚才gāngcái': 'Hace un momento',
  '刚刚gānggāng': 'Justo ahora',
  '干净gānjìng': 'Limpio',
  '感冒gǎnmào': 'Resfriado',
  '高铁gāotiě': 'Tren de alta velocidad',
  '更gèng': 'Más',
  '根据gēnjù': 'Según',
  '公斤gōngjīn': 'Kilogramo',
  '公园gōngyuán': 'Parque',
  '工作日gōngzuòrì': 'Día laboral',
  '刮guā': 'Soplar (viento)',
  '关guān': 'Cerrar',
  '关机guānjī': 'Apagar (dispositivo)',
  '关系guānxì': 'Relación',
  '关心guānxīn': 'Preocuparse por',
  '关于guānyú': 'Sobre / Acerca de',
  '关注guānzhù': 'Prestar atención',
  '国家guójiā': 'País',
  '过节guòjié': 'Celebrar festival',
  '过去guòqù': 'Pasado',
  '故事gùshi': 'Historia',
  '海hǎi': 'Mar',
  '害怕hàipà': 'Tener miedo',
  '好多hǎoduō': 'Muchos',
  '好久hǎojiǔ': 'Mucho tiempo',
  '号码hàomǎ': 'Número',
  '好像hǎoxiàng': 'Parecer',
  '河hé': 'Río',
  '黑板hēibǎn': 'Pizarra',
  '合适héshì': 'Adecuado',
  '红绿灯hóng-lǜdēng': 'Semáforo',
  '后来hòulái': 'Después',
  '后年hòunián': 'Pasado mañana (año)',
  '后天hòutiān': 'Pasado mañana',
  '画家huàjiā': 'Pintor',
  '还huán': 'Devolver',
  '换huàn': 'Cambiar',
  '黄色huángsè': 'Color amarillo',
  '环境huánjìng': 'Ambiente',
  '欢迎huānyíng': 'Bienvenido',
  '花园huāyuán': 'Jardín',
  '会huì': 'Reunión',
  '回答huídá': 'Responder',
  '会议huìyì': 'Conferencia',
  '或huò': 'O',
  '或者huòzhě': 'O',
  '护照hùzhào': 'Pasaporte',
  '极jí': 'Extremadamente',
  '急jí': 'Urgente',
  '记jì': 'Recordar',
  '季jì': 'Estación',
  '鸡jī': 'Pollo',
  '加jiā': 'Añadir',
  '检查jiǎnchá': 'Revisar',
  '坚持jiānchí': 'Insistir',
  '简单jiǎndān': 'Simple',
  '讲jiǎng': 'Hablar',
  '健康jiànkāng': 'Saludable',
  '见面jiànmiàn': 'Reunirse',
  '检票jiǎnpiào': 'Revisar boleto',
  '角jiǎo': 'Esquina / 10 céntimos',
  '脚jiǎo': 'Pie',
  '假期jiàqī': 'Vacaciones',
  '节jié': 'Festival',
  '借jiè': 'Prestar',
  '接jiē': 'Recibir',
  '街jiē': 'Calle',
  '结婚jiéhūn': 'Casarse',
  '解决jiějué': 'Resolver',
  '姐妹jiěmèi': 'Hermanas',
  '节目jiémù': 'Programa',
  '节日jiérì': 'Festival',
  '结束jiéshù': 'Terminar',
  '几乎jīhū': 'Casi',
  '机会jīhuì': 'Oportunidad',
  '季节jìjié': 'Estación del año',
  '斤jīn': 'Jin (500g)',
  '经过jīngguò': 'Pasar por',
  '经理jīnglǐ': 'Gerente',
  '旧jiù': 'Viejo',
  '久jiǔ': 'Mucho tiempo',
  '酒jiǔ': 'Licor',
  '句jù': 'Clasificador (frase)',
  '决定juédìng': 'Decidir',
  '句子jùzi': 'Oración',
  '卡kǎ': 'Tarjeta',
  '开花kāihuā': 'Florecer',
  '开会kāihuì': 'Tener reunión',
  '开机kāijī': 'Encender',
  '开心kāixīn': 'Feliz',
  '看来kànlái': 'Parece que',
  '刻kè': 'Cuarto de hora',
  '可kě': 'Pero',
  '渴kě': 'Sediento',
  '可爱kěài': 'Lindo',
  '课本kèběn': 'Libro de texto',
  '客人kèrén': 'Invitado',
  '可是kěshì': 'Pero',
  '课文kèwén': 'Texto (lección)',
  '空调kōngtiáo': 'Aire acondicionado',
  '哭kū': 'Llorar',
  '筷子kuàizi': 'Palillos',
  '矿泉水kuàngquánshuǐ': 'Agua mineral',
  '来自láizì': 'Venir de',
  '蓝lán': 'Azul',
  '老lǎo': 'Viejo',
  '老人lǎorén': 'Anciano',
  '练liàn': 'Practicar',
  '脸liǎn': 'Cara',
  '辆liàng': 'Clasificador (vehículo)',
  '凉快liángkuai': 'Fresco',
  '练习liànxí': 'Practicar',
  '聊liáo': 'Charlar',
  '了解liǎojiě': 'Entender',
  '聊天儿liáotiānr': 'Charlar',
  '离开líkāi': 'Irse',
  '邻居línjū': 'Vecino',
  '历史lìshǐ': 'Historia',
  '留学liúxué': 'Estudiar en el extranjero',
  '留学生liúxuéshēng': 'Estudiante extranjero',
  '礼物lǐwù': 'Regalo',
  '楼梯lóutī': 'Escaleras',
  '路边lùbiān': 'Al lado del camino',
  '路口lùkǒu': 'Cruce',
  '马mǎ': 'Caballo',
  '马路mǎlù': 'Calle',
  '满意mǎnyì': 'Satisfecho',
  '毛máo': 'Jiao (10 céntimos)',
  '马上mǎshàng': 'Inmediatamente',
  '米mǐ': 'Metro',
  '面前miànqián': 'Delante',
  '明白míngbai': 'Entender',
  '名单míngdān': 'Lista',
  '名人míngrén': 'Persona famosa',
  '南nán': 'Sur',
  '难nán': 'Difícil',
  '南方nánfāng': 'Sur',
  '难过nánguò': 'Triste',
  '难看nánkàn': 'Feo',
  '男人nánrén': 'Hombre',
  '男生nánshēng': 'Estudiante masculino',
  '难题nántí': 'Problema difícil',
  '难听nántīng': 'Desagradable de oír',
  '年级niánjí': 'Grado',
  '年轻niánqīng': 'Joven',
  '牛niú': 'Vaca',
  '努力nǔlì': 'Esforzarse',
  '女人nǚrén': 'Mujer',
  '女生nǚshēng': 'Estudiante femenina',
  '爬pá': 'Escalar',
  '怕pà': 'Temer',
  '拍照pāizhào': 'Tomar fotos',
  '胖pàng': 'Gordo',
  '盘子pánzi': 'Plato',
  '啤酒píjiǔ': 'Cerveza',
  '平时píngshí': 'Normalmente',
  '瓶子píngzi': 'Botella',
  '骑qí': 'Montar',
  '起qǐ': 'Levantar',
  '铅笔qiānbǐ': 'Lápiz',
  '前年qiánnián': 'Antepasado año',
  '前天qiántiān': 'Anteayer',
  '汽车qìchē': 'Automóvil',
  '起飞qǐfēi': 'Despegar',
  '奇怪qíguài': 'Extraño',
  '清楚qīngchu': 'Claro',
  '请假qǐngjià': 'Pedir permiso',
  '请客qǐngkè': 'Invitar',
  '其实qíshí': 'En realidad',
  '其他qítā': 'Otros',
  '球场qiúchǎng': 'Cancha',
  '秋天qiūtiān': 'Otoño',
  '裙子qúnzi': 'Falda',
  '然后ránhòu': 'Luego',
  '认得rènde': 'Reconocer',
  '认为rènwéi': 'Pensar que',
  '认真rènzhēn': 'Serio',
  '热情rèqíng': 'Entusiasta',
  '容易róngyì': 'Fácil',
  '如果rúguǒ': 'Si',
  '伞sǎn': 'Paraguas',
  '扫sǎo': 'Barrer',
  '沙发shāfā': 'Sofá',
  '山shān': 'Montaña',
  '上衣shàngyī': 'Chaqueta',
  '勺子sháozi': 'Cuchara',
  '身边shēnbiān': 'Al lado',
  '声shēng': 'Sonido',
  '身高shēngāo': 'Estatura',
  '生活shēnghuó': 'Vida',
  '生气shēngqì': 'Enojarse',
  '声音shēngyīn': 'Voz',
  '市shì': 'Ciudad',
  '试shì': 'Probar',
  '室shì': 'Habitación',
  '世界shìjiè': 'Mundo',
  '受shòu': 'Sufrir',
  '瘦shòu': 'Delgado',
  '收shōu': 'Recibir',
  '受到shòudào': 'Recibir',
  '收到shōudào': 'Recibir',
  '树shù': 'Árbol',
  '刷shuā': 'Cepillar',
  '双shuāng': 'Par',
  '水平shuǐpíng': 'Nivel',
  '叔叔shūshu': 'Tío',
  '数学shùxué': 'Matemáticas',
  '四季sìjì': 'Cuatro estaciones',
  '司机sījī': 'Conductor',
  '太阳tàiyáng': 'Sol',
  '糖táng': 'Azúcar / Dulce',
  '特别tèbié': 'Especial',
  '甜tián': 'Dulce',
  '跳tiào': 'Saltar',
  '提高tígāo': 'Mejorar',
  '挺tǐng': 'Bastante',
  '听说tīngshuō': 'Oír decir',
  '体育tǐyù': 'Educación física',
  '体育馆tǐyùguǎn': 'Gimnasio',
  '同事tóngshì': 'Colega',
  '同意tóngyì': 'Estar de acuerdo',
  '头发tóufa': 'Cabello',
  '腿tuǐ': 'Pierna',
  '突然tūrán': 'De repente',
  '图书馆túshūguǎn': 'Biblioteca',
  '外地wàidì': 'Otra ciudad',
  '外卖wàimài': 'Comida para llevar',
  '外语wàiyǔ': 'Idioma extranjero',
  '碗wǎn': 'Bol',
  '完成wánchéng': 'Completar',
  '晚点wǎndiǎn': 'Retrasarse',
  '忘记wàngjì': 'Olvidar',
  '网球wǎngqiú': 'Tenis',
  '网站wǎngzhàn': 'Sitio web',
  '晚会wǎnhuì': 'Fiesta nocturna',
  '为wèi': 'Para',
  '为了wèile': 'Para',
  '卫生间wèishēngjiān': 'Baño',
  '文化wénhuà': 'Cultura',
  '屋子wūzi': 'Habitación',
  '西xī': 'Oeste',
  '喜爱xǐài': 'Adorar',
  '先xiān': 'Primero',
  '向xiàng': 'Hacia',
  '像xiàng': 'Parecer',
  '相机xiàngjī': 'Cámara',
  '香蕉xiāngjiāo': 'Plátano',
  '相信xiāngxìn': 'Creer',
  '箱子xiāngzi': 'Caja / Maleta',
  '小区xiǎoqū': 'Vecindario',
  '小心xiǎoxīn': 'Tener cuidado',
  '校园xiàoyuán': 'Campus',
  '校长xiàozhǎng': 'Director',
  '夏天xiàtiān': 'Verano',
  '西北xīběi': 'Noroeste',
  '鞋xié': 'Zapatos',
  '西方xīfāng': 'Occidente',
  '西瓜xīguā': 'Sandía',
  '习惯xíguàn': 'Hábito',
  '信xìn': 'Carta / Creer',
  '西南xīnán': 'Suroeste',
  '行xíng': 'Funcionar',
  '行李xíngli': 'Equipaje',
  '兴趣xìngqù': 'Interés',
  '心里xīnlǐ': 'En el corazón',
  '新年xīnnián': 'Año Nuevo',
  '新闻xīnwén': 'Noticias',
  '新鲜xīnxiān': 'Fresco',
  '信用卡xìnyòngkǎ': 'Tarjeta de crédito',
  '休假xiūjià': 'Tomar vacaciones',
  '洗衣机xǐyījī': 'Lavadora',
  '洗澡xǐzǎo': 'Bañarse',
  '选xuǎn': 'Elegir',
  '选择xuǎnzé': 'Elegir',
  '学期xuéqī': 'Semestre',
  '需要xūyào': 'Necesitar',
  '牙yá': 'Diente',
  '羊yáng': 'Oveja',
  '养yǎng': 'Criar',
  '要求yāoqiú': 'Requerir',
  '牙刷yáshuā': 'Cepillo de dientes',
  '页yè': 'Página',
  '一般yìbān': 'General',
  '一边yìbiān': 'Mientras',
  '一定yídìng': 'Definitivamente',
  '一共yígòng': 'En total',
  '以后yǐhòu': 'Después',
  '一块儿yíkuàir': 'Juntos',
  '应该yīnggāi': 'Deber',
  '影响yǐngxiǎng': 'Influencia',
  '银行yínháng': 'Banco',
  '银行卡yínhángkǎ': 'Tarjeta bancaria',
  '饮料yǐnliào': 'Bebida',
  '音乐yīnyuè': 'Música',
  '以前yǐqián': 'Antes',
  '以上yǐshàng': 'Arriba',
  '以外yǐwài': 'Excepto',
  '以为yǐwéi': 'Pensar equivocadamente',
  '以下yǐxià': 'Abajo',
  '一样yíyàng': 'Igual',
  '一直yìzhí': 'Siempre',
  '用yòng': 'Usar',
  '又yòu': 'Otra vez',
  '有关yǒuguān': 'Relacionado',
  '邮件yóujiàn': 'Correo',
  '游客yóukè': 'Turista',
  '有名yǒumíng': 'Famoso',
  '游戏yóuxì': 'Juego',
  '邮箱yóuxiāng': 'Buzón',
  '有用yǒuyòng': 'Útil',
  '园yuán': 'Jardín',
  '员yuán': 'Sufijo (miembro)',
  '愿意yuànyì': 'Estar dispuesto',
  '遇到yùdào': 'Encontrarse con',
  '越yuè': 'Más',
  '月亮yuèliang': 'Luna',
  '遇见yùjiàn': 'Encontrarse',
  '羽毛球yǔmáoqiú': 'Bádminton',
  '运动会yùndònghuì': 'Competencia deportiva',
  '运动员yùndòngyuán': 'Atleta',
  '语言yǔyán': 'Idioma',
  '雨衣yǔyī': 'Impermeable',
  '脏zāng': 'Sucio',
  '咱们zánmen': 'Nosotros (inclusivo)',
  '怎么办zěnmebàn': 'Qué hacer',
  '怎样zěnyàng': 'Cómo',
  '站zhàn': 'Estar de pie',
  '长zhǎng': 'Crecer',
  '张zhāng': 'Clasificador (papel)',
  '照zhào': 'Tomar foto',
  '照顾zhàogù': 'Cuidar',
  '着急zháojí': 'Ansioso',
  '照片zhàopiàn': 'Foto',
  '照相zhàoxiàng': 'Tomar foto',
  '只zhǐ': 'Solo',
  '纸zhǐ': 'Papel',
  '只能zhǐnéng': 'Solo poder',
  '直到zhídào': 'Hasta',
  '只是zhǐshì': 'Solo / Solamente',
  '只要zhǐyào': 'Con tal de que',
  '只有zhǐyǒu': 'Solo',
  '种zhǒng': 'Tipo',
  '中zhōng': 'Centro',
  '中间zhōngjiān': 'En medio',
  '重要zhòngyào': 'Importante',
  '终于zhōngyú': 'Finalmente',
  '周末zhōumò': 'Fin de semana',
  '主要zhǔyào': 'Principal',
  '注意zhùyì': 'Prestar atención',
  '住院zhùyuàn': 'Hospitalizar',
  '子zi': 'Sufijo',
  '字典zìdiǎn': 'Diccionario',
  '自行车zìxíngchē': 'Bicicleta',
  '总zǒng': 'Total',
  '总是zǒngshì': 'Siempre',
  '嘴zuǐ': 'Boca',
  '最好zuìhǎo': 'Mejor',
  '最后zuìhòu': 'Último',
  '最近zuìjìn': 'Recientemente',
  '做客zuòkè': 'Visitar',
  '作业zuòyè': 'Tarea',

  // HSK 4 (1000 palabras) - Parte 1
  '啊ā': 'Ah (exclamación)',
  '爱情àiqíng': 'Amor romántico',
  '爱心àixīn': 'Amor / Compasión',
  '按àn': 'Presionar',
  '安检ānjiǎn': 'Control de seguridad',
  '安排ānpái': 'Organizar',
  '按时ànshí': 'A tiempo',
  '按照ànzhào': 'Según',
  '白酒báijiǔ': 'Licor blanco',
  '棒bàng': 'Excelente',
  '办公bàngōng': 'Trabajar en oficina',
  '办理bànlǐ': 'Procesar',
  '办事bànshì': 'Hacer trámites',
  '抱bào': 'Abrazar',
  '保护bǎohù': 'Proteger',
  '报考bàokǎo': 'Inscribirse (examen)',
  '报名bàomíng': 'Registrarse',
  '抱歉bàoqiàn': 'Lo siento',
  '保证bǎozhèng': 'Garantizar',
  '倍bèi': 'Veces (múltiplo)',
  '背bēi': 'Llevar en la espalda',
  '背包bēibāo': 'Mochila',
  '北部běibù': 'Parte norte',
  '笨bèn': 'Tonto',
  '本科běnkē': 'Licenciatura',
  '本来běnlái': 'Originalmente',
  '便于biànyú': 'Conveniente para',
  '表biǎo': 'Tabla / Reloj',
  '表格biǎogé': 'Formulario',
  '表示biǎoshì': 'Expresar',
  '表现biǎoxiàn': 'Desempeño',
  '表扬biǎoyáng': 'Elogiar',
  '标准biāozhǔn': 'Estándar',
  '并bìng': 'Y / Además',
  '饼干bǐnggān': 'Galleta',
  '并且bìngqiě': 'Y además',
  '笔试bǐshì': 'Examen escrito',
  '毕业bìyè': 'Graduarse',
  '毕业生bìyèshēng': 'Graduado',
  '鼻子bízi': 'Nariz',
  '播放bōfàng': 'Reproducir',
  '博士bóshì': 'Doctor (PhD)',
  '步bù': 'Paso',
  '部bù': 'Parte / Departamento',
  '不必búbì': 'No es necesario',
  '不便búbiàn': 'Inconveniente',
  '不得不bùdébù': 'Tener que',
  '不断búduàn': 'Continuamente',
  '部分bùfen': 'Parte',
  '不够búgòu': 'No suficiente',
  '不管bùguǎn': 'No importa',
  '不光bùguāng': 'No solo',
  '不过búguò': 'Pero',
  '不仅bùjǐn': 'No solo',
  '不论búlùn': 'Sin importar',
  '不满bùmǎn': 'Insatisfecho',
  '部门bùmén': 'Departamento',
  '不如bùrú': 'No tan bueno como',
  '擦cā': 'Limpiar',
  '猜cāi': 'Adivinar',
  '材料cáiliào': 'Material',
  '参观cānguān': 'Visitar',
  '参赛cānsài': 'Competir',
  '餐厅cāntīng': 'Comedor',
  '操场cāochǎng': 'Patio de juegos',
  '厕所cèsuǒ': 'Baño',
  '查看chákàn': 'Revisar',
  '厂chǎng': 'Fábrica',
  '场chǎng': 'Clasificador (evento)',
  '产生chǎnshēng': 'Producir',
  '超过chāoguò': 'Exceder',
  '茶叶cháyè': 'Hojas de té',
  '差（一）点儿chà(yì)diǎnr': 'Casi',
  '查找cházhǎo': 'Buscar',
  '城chéng': 'Ciudad',
  '乘chéng': 'Multiplicar / Viajar en',
  '成功chénggōng': 'Éxito',
  '乘客chéngkè': 'Pasajero',
  '诚实chéngshí': 'Honesto',
  '成为chéngwéi': 'Convertirse en',
  '乘坐chéngzuò': 'Viajar en',
  '车速chēsù': 'Velocidad del vehículo',
  '车位chēwèi': 'Espacio de estacionamiento',
  '迟chí': 'Tarde',
  '吃惊chījīng': 'Sorprenderse',
  '重chóng': 'Repetir',
  '重新chóngxīn': 'De nuevo',
  '窗chuāng': 'Ventana',
  '窗户chuānghu': 'Ventana',
  '出差chūchāi': 'Viaje de negocios',
  '厨房chúfáng': 'Cocina',
  '吹chuī': 'Soplar',
  '出口chūkǒu': 'Salida',
  '厨师chúshī': 'Cocinero',
  '出现chūxiàn': 'Aparecer',
  '出行chūxíng': 'Viajar',
  '出租chūzū': 'Alquilar',
  '此cǐ': 'Este',
  '此次cǐcì': 'Esta vez',
  '此外cǐwài': 'Además',
  '词语cíyǔ': 'Palabra',
  '从此cóngcǐ': 'Desde entonces',
  '从来cónglái': 'Nunca',
  '从中cóngzhōng': 'De entre',
  '粗cū': 'Grueso',
  '存cún': 'Guardar',
  '村cūn': 'Aldea',
  '错过cuòguò': 'Perder (oportunidad)',
  '错误cuòwù': 'Error',
  '粗心cūxīn': 'Descuidado',
  '答dá': 'Responder',
  '打招呼dǎzhāohu': 'Saludar',
  '答案dáàn': 'Respuesta',
  '大巴dàbā': 'Autobús',
  '打败dǎbài': 'Derrotar',
  '大大dàdà': 'Mucho',
  '达到dádào': 'Alcanzar',
  '打工dǎgōng': 'Trabajar (temporal)',
  '戴dài': 'Llevar puesto',
  '待dāi': 'Quedarse',
  '大夫dàifu': 'Doctor',
  '袋子dàizi': 'Bolsa',
  '大量dàliàng': 'Gran cantidad',
  '当dāng': 'Ser / Actuar como',
  '当时dāngshí': 'En ese momento',
  '单位dānwèi': 'Unidad / Lugar de trabajo',
  '倒dào': 'Verter',
  '道dào': 'Camino',
  '刀dāo': 'Cuchillo',
  '到底dàodǐ': 'Finalmente / En el fondo',
  '到来dàolái': 'Llegar',
  '道路dàolù': 'Carretera',
  '道歉dàoqiàn': 'Disculparse',
  '导游dǎoyóu': 'Guía turístico',
  '打扰dǎrǎo': 'Molestar',
  '大赛dàsài': 'Gran competencia',
  '大厅dàtīng': 'Sala / Lobby',
  '打印dǎyìn': 'Imprimir',
  '答应dāying': 'Prometer',
  '打印机dǎyìnjī': 'Impresora',
  '大约dàyuē': 'Aproximadamente',
  '打折dǎzhé': 'Descuento',
  '打针dǎzhēn': 'Inyectar',
  '大自然dàzìrán': 'Naturaleza',
  '等děng': 'Etcétera',
  '等到děngdào': 'Esperar hasta',
  '登机dēngjī': 'Abordar',
  '得意déyì': 'Orgulloso',
  '底dǐ': 'Fondo',
  '低dī': 'Bajo',
  '电动车diàndòngchē': 'Vehículo eléctrico',
  '点名diǎnmíng': 'Pasar lista',
  '电视剧diànshìjù': 'Serie de TV',
  '点头diǎntóu': 'Asentir',
  '掉diào': 'Caer',
  '调查diàochá': 'Investigar',
  '低价dījià': 'Precio bajo',
  '订dìng': 'Reservar',
  '定dìng': 'Decidir',
  '地球dìqiú': 'Tierra (planeta)',
  '低温dīwēn': 'Temperatura baja',
  '底下dǐxia': 'Debajo',
  '低于dīyú': 'Menor que',
  '地址dìzhǐ': 'Dirección',
  '东部dōngbù': 'Parte este',
  '动车dòngchē': 'Tren de alta velocidad',
  '动作dòngzuò': 'Acción / Movimiento',
  '短信duǎnxìn': 'Mensaje de texto',
  '堵车dǔchē': 'Embotellamiento',
  '队duì': 'Equipo',
  '对方duìfāng': 'La otra parte',
  '对面duìmiàn': 'Enfrente',
  '对于duìyú': 'Con respecto a',
  '队员duìyuán': 'Miembro del equipo',
  '队长duìzhǎng': 'Capitán',
  '度假dùjià': 'Vacaciones',
  '顿dùn': 'Clasificador (comida)',
  '多么duōme': 'Qué (exclamación)',
  '多数duōshù': 'Mayoría',
  '多样duōyàng': 'Diverso',
  '读者dúzhě': 'Lector',
  '肚子dùzi': 'Estómago / Vientre',
  '而ér': 'Y / Pero',
  '儿童értóng': 'Niño',
  '法fǎ': 'Ley / Método',
  '发出fāchū': 'Emitir',
  '法律fǎlǜ': 'Ley',
  '烦fán': 'Molesto',
  '反对fǎnduì': 'Oponerse',
  '房东fángdōng': 'Propietario',
  '方面fāngmiàn': 'Aspecto',
  '放弃fàngqì': 'Abandonar',
  '方式fāngshì': 'Manera',
  '放松fàngsōng': 'Relajarse',
  '房租fángzū': 'Alquiler',
  '烦恼fánnǎo': 'Preocupación',
  '翻译fānyì': 'Traducir',
  '发送fāsòng': 'Enviar',
  '费fèi': 'Tarifa',
  '费用fèiyong': 'Costo',
  '份fèn': 'Clasificador (copia)',
  '丰富fēngfù': 'Rico / Abundante',
  '风景fēngjǐng': 'Paisaje',
  '分数fēnshù': 'Calificación',
  '分为fēnwéi': 'Dividir en',
  '否则fǒuzé': 'De lo contrario',
  '幅fú': 'Clasificador (cuadro)',
  '付fù': 'Pagar',
  '符合fúhé': 'Cumplir con',
  '父母fùmǔ': 'Padres',
  '父女fùnǚ': 'Padre e hija',
  '父亲fùqīn': 'Padre',
  '复印fùyìn': 'Fotocopiar',
  '复杂fùzá': 'Complicado',
  '负责fùzé': 'Responsable',
  '负责人fùzérén': 'Persona responsable',
  '父子fùzǐ': 'Padre e hijo',
  '改gǎi': 'Cambiar',
  '改变gǎibiàn': 'Cambiar',
  '赶gǎn': 'Apresurarse',
  '敢gǎn': 'Atreverse',
  '感gǎn': 'Sentir',
  '干gān': 'Seco',
  '干杯gānbēi': 'Brindis',
  '感动gǎndòng': 'Conmovido',
  '钢琴gāngqín': 'Piano',
  '干活儿gànhuór': 'Trabajar',
  '赶紧gǎnjǐn': 'Apresurarse',
  '感觉gǎnjué': 'Sentir',
  '赶快gǎnkuài': 'Rápidamente',
  '感情gǎnqíng': 'Sentimiento',
  '感人gǎnrén': 'Conmovedor',
  '赶上gǎnshàng': 'Alcanzar',
  '感受gǎnshòu': 'Sentir',
  '感谢gǎnxiè': 'Agradecer',
  '高价gāojià': 'Precio alto',
  '高考gāokǎo': 'Examen de ingreso',
  '高速gāosù': 'Alta velocidad',
  '高温gāowēn': 'Temperatura alta',
  '高于gāoyú': 'Mayor que',
  '各gè': 'Cada',
  '胳膊gēbo': 'Brazo',
  '各地gèdì': 'Varios lugares',
  '各个gègè': 'Cada uno',
  '更加gèngjiā': 'Aún más',
  '歌声gēshēng': 'Canto',
  '歌手gēshǒu': 'Cantante',
  '各位gèwèi': 'Todos (formal)',
  '各种gèzhǒng': 'Varios tipos',
  '共gòng': 'Juntos / Total',
  '工厂gōngchǎng': 'Fábrica',
  '功夫gōngfu': 'Kung fu / Tiempo',
  '公共gōnggòng': 'Público',
  '功课gōngkè': 'Tarea',
  '公里gōnglǐ': 'Kilómetro',
  '公路gōnglù': 'Carretera',
  '工人gōngrén': 'Obrero',
  '共同gòngtóng': 'Común',
  '工资gōngzī': 'Salario',
  '够gòu': 'Suficiente',
  '购买gòumǎi': 'Comprar',
  '购物gòuwù': 'Ir de compras',
  '挂guà': 'Colgar',
  '管guǎn': 'Administrar',
  '逛guàng': 'Pasear',
  '光guāng': 'Luz',
  '广播guǎngbō': 'Transmitir',
  '广告guǎnggào': 'Anuncio',
  '关键guānjiàn': 'Clave',
  '观看guānkàn': 'Ver',
  '管理guǎnlǐ': 'Administrar',
  '观众guānzhòng': 'Audiencia',
  '规定guīdìng': 'Regla',
  '估计gūjì': 'Estimar',
  '顾客gùkè': 'Cliente',
  '鼓励gǔlì': 'Animar',
  '姑娘gūniang': 'Chica',
  '过程guòchéng': 'Proceso',
  '国籍guójí': 'Nacionalidad',
  '国际guójì': 'Internacional',
  '果汁guǒzhī': 'Jugo',
  '故意gùyì': 'A propósito',

  // HSK 4 - Parte 2
  '害羞hàixiū': 'Tímido',
  '海洋hǎiyáng': 'Océano',
  '汗hàn': 'Sudor',
  '喊hǎn': 'Gritar',
  '航班hángbān': 'Vuelo',
  '寒假hánjià': 'Vacaciones de invierno',
  '寒冷hánlěng': 'Frío',
  '好处hǎochù': 'Beneficio',
  '好好hǎohǎo': 'Bien',
  '好笑hǎoxiào': 'Gracioso',
  '合格hégé': 'Calificado',
  '盒子hézi': 'Caja',
  '红包hóngbāo': 'Sobre rojo',
  '厚hòu': 'Grueso',
  '后悔hòuhuǐ': 'Arrepentirse',
  '坏处huàichù': 'Desventaja',
  '怀疑huáiyí': 'Dudar',
  '话剧huàjù': 'Obra de teatro',
  '环保huánbǎo': 'Protección ambiental',
  '换乘huànchéng': 'Transbordo',
  '回复huífù': 'Responder',
  '回信huíxìn': 'Responder carta',
  '回忆huíyì': 'Recordar',
  '会员huìyuán': 'Miembro',
  '互联网hùliánwǎng': 'Internet',
  '活huó': 'Vivir',
  '货huò': 'Mercancía',
  '火huǒ': 'Fuego',
  '获得huòdé': 'Obtener',
  '活动huódòng': 'Actividad',
  '获奖huòjiǎng': 'Ganar premio',
  '活泼huópō': 'Vivaz',
  '获取huòqǔ': 'Obtener',
  '忽然hūrán': 'De repente',
  '护士hùshi': 'Enfermera',
  '互相hùxiāng': 'Mutuamente',
  '既jì': 'Ya / Puesto que',
  '寄jì': 'Enviar por correo',
  '假jiǎ': 'Falso',
  '加班jiābān': 'Trabajar horas extra',
  '价格jiàgé': 'Precio',
  '家具jiājù': 'Muebles',
  '加快jiākuài': 'Acelerar',
  '减jiǎn': 'Reducir',
  '降jiàng': 'Bajar',
  '奖jiǎng': 'Premio',
  '江jiāng': 'Río',
  '将jiāng': 'Futuro / Va a',
  '降低jiàngdī': 'Reducir',
  '降价jiàngjià': 'Rebajar precio',
  '奖金jiǎngjīn': 'Bono',
  '将来jiānglái': 'Futuro',
  '降落jiàngluò': 'Aterrizar',
  '降温jiàngwēn': 'Bajar temperatura',
  '奖学金jiǎngxuéjīn': 'Beca',
  '将要jiāngyào': 'Va a',
  '减轻jiǎnqīng': 'Aligerar',
  '减少jiǎnshǎo': 'Reducir',
  '健身jiànshēn': 'Hacer ejercicio',
  '健身房jiànshēnfáng': 'Gimnasio',
  '建议jiànyì': 'Sugerir',
  '交jiāo': 'Entregar',
  '骄傲jiāoào': 'Orgulloso',
  '交警jiāojǐng': 'Policía de tránsito',
  '教练jiàoliàn': 'Entrenador',
  '交流jiāoliú': 'Intercambiar',
  '郊区jiāoqū': 'Suburbios',
  '教师jiàoshī': 'Profesor',
  '教授jiàoshòu': 'Profesor universitario',
  '交通jiāotōng': 'Tráfico',
  '教学jiàoxué': 'Enseñanza',
  '教育jiàoyù': 'Educación',
  '叫作jiàozuò': 'Llamarse',
  '价钱jiàqián': 'Precio',
  '加强jiāqiáng': 'Fortalecer',
  '假日jiàrì': 'Día feriado',
  '加入jiārù': 'Unirse',
  '加上jiāshàng': 'Más',
  '家庭jiātíng': 'Familia',
  '家乡jiāxiāng': 'Pueblo natal',
  '加油jiāyóu': 'Cargar gasolina / Ánimo',
  '加油站jiāyóuzhàn': 'Gasolinera',
  '家长jiāzhǎng': 'Padre (de estudiante)',
  '基本jīběn': 'Básico',
  '基本上jīběnshàng': 'Básicamente',
  '基础jīchǔ': 'Base',
  '激动jīdòng': 'Emocionado',
  '街道jiēdào': 'Calle',
  '结果jiéguǒ': 'Resultado',
  '节假日jiéjiàrì': 'Día festivo',
  '解释jiěshì': 'Explicar',
  '接受jiēshòu': 'Aceptar',
  '节约jiéyuē': 'Ahorrar',
  '结账jiézhàng': 'Pagar la cuenta',
  '接着jiēzhe': 'Luego',
  '计划jìhuà': 'Plan',
  '积极jījí': 'Activo',
  '积累jīlěi': 'Acumular',
  '仅jǐn': 'Solo',
  '精彩jīngcǎi': 'Maravilloso',
  '警察jǐngchá': 'Policía',
  '景点jǐngdiǎn': 'Lugar turístico',
  '经济jīngjì': 'Economía',
  '京剧jīngjù': 'Ópera de Pekín',
  '经历jīnglì': 'Experiencia',
  '景区jǐngqū': 'Zona turística',
  '竟然jìngrán': 'Inesperadamente',
  '景色jǐngsè': 'Paisaje',
  '尽管jǐnguǎn': 'Aunque',
  '经验jīngyàn': 'Experiencia',
  '竞争jìngzhēng': 'Competir',
  '镜子jìngzi': 'Espejo',
  '今后jīnhòu': 'En el futuro',
  '仅仅jǐnjǐn': 'Solamente',
  '进入jìnrù': 'Entrar',
  '进行jìnxíng': 'Realizar',
  '紧张jǐnzhāng': 'Nervioso',
  '禁止jìnzhǐ': 'Prohibir',
  '既然jìrán': 'Ya que',
  '及时jíshí': 'A tiempo',
  '即使jíshǐ': 'Aunque',
  '技术jìshù': 'Tecnología',
  '究竟jiūjìng': 'Después de todo',
  '就是jiùshì': 'Exactamente',
  '继续jìxù': 'Continuar',
  '记者jìzhě': 'Periodista',
  '聚jù': 'Reunirse',
  '举jǔ': 'Levantar',
  '举办jǔbàn': 'Organizar',
  '聚餐jùcān': 'Comer juntos',
  '聚会jùhuì': 'Reunión',
  '拒绝jùjué': 'Rechazar',
  '距离jùlí': 'Distancia',
  '举例jǔlì': 'Dar ejemplo',
  '举行jǔxíng': 'Realizar',
  '剧院jùyuàn': 'Teatro',
  '开玩笑kāiwánxiào': 'Bromear',
  '看法kànfǎ': 'Opinión',
  '烤kǎo': 'Asar',
  '考虑kǎolǜ': 'Considerar',
  '考生kǎoshēng': 'Examinado',
  '咳ké': 'Toser',
  '克kè': 'Gramo',
  '棵kē': 'Clasificador (árbol)',
  '课程kèchéng': 'Curso',
  '科技kējì': 'Ciencia y tecnología',
  '肯定kěndìng': 'Seguramente',
  '客气kèqi': 'Cortés',
  '咳嗽késou': 'Toser',
  '课堂kètáng': 'Salón de clases',
  '客厅kètīng': 'Sala',
  '可惜kěxī': 'Lástima',
  '科学kēxué': 'Ciencia',
  '空kòng': 'Tiempo libre',
  '空kōng': 'Vacío',
  '恐怕kǒngpà': 'Me temo que',
  '空气kōngqì': 'Aire',
  '口语kǒuyǔ': 'Lengua hablada',
  '苦kǔ': 'Amargo',
  '快餐kuàicān': 'Comida rápida',
  '快递kuàidì': 'Entrega rápida',
  '快速kuàisù': 'Rápido',
  '困kùn': 'Cansado',
  '困难kùnnan': 'Difícil',
  '辣là': 'Picante',
  '拉lā': 'Tirar',
  '来不及láibují': 'No tener tiempo',
  '来得及láidejí': 'Tener tiempo',
  '垃圾lājī': 'Basura',
  '懒lǎn': 'Perezoso',
  '浪费làngfèi': 'Desperdiciar',
  '浪漫làngmàn': 'Romántico',
  '老虎lǎohǔ': 'Tigre',
  '老家lǎojiā': 'Pueblo natal',
  '老年lǎonián': 'Vejez',
  '老是lǎoshì': 'Siempre',
  '冷静lěngjìng': 'Calmado',
  '俩liǎ': 'Dos (personas)',
  '连lián': 'Incluso',
  '凉liáng': 'Fresco',
  '量liáng': 'Medir',
  '亮liàng': 'Brillante',
  '两liǎng': 'Tael (50g)',
  '联系liánxì': 'Contactar',
  '列liè': 'Lista',
  '理发lǐfà': 'Cortar pelo',
  '厉害lìhai': 'Poderoso',
  '理解lǐjiě': 'Comprender',
  '礼貌lǐmào': 'Cortesía',
  '另lìng': 'Otro',
  '零下língxià': 'Bajo cero',
  '零花钱línghuāqián': 'Dinero de bolsillo',
  '零钱língqián': 'Cambio',
  '零食língshí': 'Snack',
  '另外lìngwài': 'Además',
  '力气lìqi': 'Fuerza',
  '例如lìrú': 'Por ejemplo',
  '留liú': 'Dejar',
  '流liú': 'Fluir',
  '流利liúlì': 'Fluido',
  '留下liúxia': 'Dejar',
  '流行liúxíng': 'Popular',
  '理想lǐxiǎng': 'Ideal',
  '例子lìzi': 'Ejemplo',
  '乱luàn': 'Desordenado',
  '旅馆lǚguǎn': 'Hotel',
  '路过lùguò': 'Pasar por',
  '旅客lǚkè': 'Viajero',
  '落luò': 'Caer',
  '律师lǜshī': 'Abogado',
  '旅行lǚxíng': 'Viajar',
  '麻烦máfan': 'Problema',
  '满mǎn': 'Lleno',
  '馒头mántou': 'Pan al vapor',
  '毛巾máojīn': 'Toalla',
  '毛衣máoyī': 'Suéter',
  '帽子màozi': 'Sombrero',
  '美měi': 'Hermoso',
  '美好měihǎo': 'Maravilloso',
  '美景měijǐng': 'Hermoso paisaje',
  '美丽měilì': 'Hermoso',
  '美食měishí': 'Comida deliciosa',
  '梦mèng': 'Sueño',
  '梦想mèngxiǎng': 'Sueño / Soñar',
  '面对miànduì': 'Enfrentar',
  '免费miǎnfèi': 'Gratis',
  '面试miànshì': 'Entrevista',
  '秒miǎo': 'Segundo',
  '密码mìmǎ': 'Contraseña',
  '民族mínzú': 'Etnia',
  '末mò': 'Final',
  '目标mùbiāo': 'Meta',
  '目的mùdì': 'Propósito',
  '目的地mùdìdì': 'Destino',
  '母女mǔnǚ': 'Madre e hija',
  '目前mùqián': 'Actualmente',
  '母亲mǔqīn': 'Madre',
  '母子mǔzǐ': 'Madre e hijo',
  '耐心nàixīn': 'Paciencia',
  '南部nánbù': 'Parte sur',
  '难道nándào': 'Acaso',
  '男士nánshì': 'Caballero',
  '难受nánshòu': 'Incómodo',
  '难忘nánwàng': 'Inolvidable',
  '男性nánxìng': 'Masculino',
  '内nèi': 'Interior',
  '内容nèiróng': 'Contenido',
  '内心nèixīn': 'Corazón',
  '能否néngfǒu': 'Si puede',
  '能够nénggòu': 'Poder',
  '能力nénglì': 'Capacidad',
  '嗯ǹg': 'Mm (afirmación)',
  '年底niándǐ': 'Fin de año',
  '年龄niánlíng': 'Edad',
  '弄nòng': 'Hacer',
  '农村nóngcūn': 'Campo',
  '暖和nuǎnhuo': 'Cálido',
  '女性nǚxìng': 'Femenino',
  '偶尔ǒuěr': 'Ocasionalmente',
  '排pái': 'Fila',
  '牌pái': 'Marca / Tarjeta',
  '拍pāi': 'Palmear',
  '排队páiduì': 'Hacer fila',
  '排球páiqiú': 'Voleibol',
  '牌子páizi': 'Marca',
  '判断pànduàn': 'Juzgar',
  '陪péi': 'Acompañar',
  '片piàn': 'Rebanada',
  '篇piān': 'Clasificador (artículo)',
  '皮肤pífū': 'Piel',
  '平常píngcháng': 'Normal',
  '乒乓球pīngpāngqiú': 'Ping pong',
  '批评pīpíng': 'Criticar',
  '脾气píqi': 'Temperamento',
  '皮鞋píxié': 'Zapatos de cuero',
  '破pò': 'Roto',
  '普遍pǔbiàn': 'Universal',
  '葡萄pútao': 'Uva',
  '葡萄酒pútaojiǔ': 'Vino',
  '普通pǔtōng': 'Ordinario',
  '普通话pǔtōnghuà': 'Mandarín',

  // HSK 4 - Parte 3 (Final)
  '气qì': 'Gas / Respirar',
  '期qī': 'Período',
  '前方qiánfāng': 'Adelante',
  '强qiáng': 'Fuerte',
  '前后qiánhòu': 'Antes y después',
  '千克qiānkè': 'Kilogramo',
  '千万qiānwàn': 'Definitivamente',
  '签证qiānzhèng': 'Visa',
  '桥qiáo': 'Puente',
  '巧qiǎo': 'Ingenioso',
  '敲qiāo': 'Golpear',
  '巧克力qiǎokèlì': 'Chocolate',
  '其次qícì': 'Luego',
  '起到qǐdào': 'Cumplir función',
  '气候qìhòu': 'Clima',
  '期末qīmò': 'Fin de semestre',
  '琴qín': 'Instrumento musical',
  '轻qīng': 'Ligero',
  '情况qíngkuàng': 'Situación',
  '青年qīngnián': 'Joven',
  '轻松qīngsōng': 'Relajado',
  '庆祝qìngzhù': 'Celebrar',
  '亲戚qīnqi': 'Pariente',
  '汽水qìshuǐ': 'Gaseosa',
  '球队qiúduì': 'Equipo deportivo',
  '球迷qiúmí': 'Fanático del deporte',
  '气温qìwēn': 'Temperatura',
  '其中qízhōng': 'Entre ellos',
  '期中qīzhōng': 'Mitad de semestre',
  '取qǔ': 'Tomar',
  '区qū': 'Distrito',
  '全quán': 'Todo',
  '全部quánbù': 'Todo',
  '全都quándōu': 'Todos',
  '全球quánqiú': 'Global',
  '全身quánshēn': 'Todo el cuerpo',
  '区别qūbié': 'Diferencia',
  '取得qǔdé': 'Obtener',
  '却què': 'Pero',
  '缺quē': 'Carecer',
  '缺点quēdiǎn': 'Defecto',
  '缺少quēshǎo': 'Faltar',
  '确实quèshí': 'Realmente',
  '取消qǔxiāo': 'Cancelar',
  '然而ránér': 'Sin embargo',
  '热闹rènao': 'Animado',
  '仍réng': 'Aún',
  '扔rēng': 'Tirar',
  '仍然réngrán': 'Todavía',
  '任何rènhé': 'Cualquier',
  '人生rénshēng': 'Vida',
  '人数rénshù': 'Número de personas',
  '任务rènwu': 'Tarea',
  '人员rényuán': 'Personal',
  '日常rìcháng': 'Diario',
  '日记rìjì': 'Diario',
  '日期rìqī': 'Fecha',
  '日子rìzi': 'Día',
  '入rù': 'Entrar',
  '入口rùkǒu': 'Entrada',
  '入学rùxué': 'Inscribirse',
  '入住rùzhù': 'Registrarse (hotel)',
  '散步sànbù': 'Pasear',
  '扫码sǎomǎ': 'Escanear código',
  '森林sēnlín': 'Bosque',
  '商量shāngliang': 'Discutir',
  '上门shàngmén': 'Visitar',
  '商品shāngpǐn': 'Mercancía',
  '伤心shāngxīn': 'Triste',
  '稍shāo': 'Ligeramente',
  '少见shǎojiàn': 'Raro',
  '少量shǎoliàng': 'Pequeña cantidad',
  '少年shàonián': 'Adolescente',
  '少数shǎoshù': 'Minoría',
  '稍微shāowēi': 'Ligeramente',
  '社会shèhuì': 'Sociedad',
  '身shēn': 'Cuerpo',
  '深shēn': 'Profundo',
  '身份证shēnfènzhèng': 'DNI',
  '剩shèng': 'Sobrar',
  '省shěng': 'Provincia',
  '生shēng': 'Nacer',
  '生shēng': 'Crudo',
  '生命shēngmìng': 'Vida',
  '生意shēngyi': 'Negocio',
  '申请shēnqǐng': 'Solicitar',
  '甚至shènzhì': 'Incluso',
  '摄氏度shèshìdù': 'Grado Celsius',
  '使shǐ': 'Hacer que',
  '失败shībài': 'Fracasar',
  '市场shìchǎng': 'Mercado',
  '十分shífēn': 'Muy',
  '是否shìfǒu': 'Si o no',
  '师傅shīfu': 'Maestro',
  '使馆shǐguǎn': 'Embajada',
  '适合shìhé': 'Adecuado',
  '实际shíjì': 'Real',
  '世纪shìjì': 'Siglo',
  '时间表shíjiānbiǎo': 'Horario',
  '实际上shíjìshàng': 'En realidad',
  '食品shípǐn': 'Alimentos',
  '视频shìpín': 'Video',
  '市区shìqū': 'Centro de la ciudad',
  '失去shīqù': 'Perder',
  '师生shīshēng': 'Maestros y estudiantes',
  '食堂shítáng': 'Comedor',
  '试题shìtí': 'Pregunta de examen',
  '失望shīwàng': 'Decepcionado',
  '食物shíwù': 'Comida',
  '适应shìyìng': 'Adaptarse',
  '使用shǐyòng': 'Usar',
  '实在shízài': 'Realmente',
  '十字路口shízìlùkǒu': 'Cruce',
  '首shǒu': 'Clasificador (canción)',
  '受不了shòubuliǎo': 'No soportar',
  '首都shǒudū': 'Capital',
  '收费shōufèi': 'Cobrar',
  '售票员shòupiàoyuán': 'Vendedor de boletos',
  '收入shōurù': 'Ingreso',
  '受伤shòushāng': 'Lesionarse',
  '收拾shōushi': 'Ordenar',
  '收听shōutīng': 'Escuchar (radio)',
  '首先shǒuxiān': 'Primero',
  '数shù': 'Número',
  '输shū': 'Perder',
  '熟shú/shóu': 'Maduro',
  '帅shuài': 'Guapo',
  '暑假shǔjià': 'Vacaciones de verano',
  '数量shùliàng': 'Cantidad',
  '树林shùlín': 'Bosque',
  '顺便shùnbiàn': 'De paso',
  '顺利shùnlì': 'Exitoso',
  '顺序shùnxù': 'Orden',
  '说法shuōfǎ': 'Forma de decir',
  '说明shuōmíng': 'Explicar',
  '说明书shuōmíngshū': 'Instrucciones',
  '硕士shuòshì': 'Maestría',
  '熟悉shúxi': 'Familiar',
  '数字shùzì': 'Número',
  '死sǐ': 'Morir',
  '算suàn': 'Contar',
  '酸suān': 'Ácido',
  '酸奶suānnǎi': 'Yogur',
  '速度sùdù': 'Velocidad',
  '随便suíbiàn': 'Como quieras',
  '随着suízhe': 'A medida que',
  '塑料sùliào': 'Plástico',
  '孙女sūnnǚ': 'Nieta',
  '孙子sūnzi': 'Nieto',
  '所有suǒyǒu': 'Todo',
  '台tái': 'Clasificador (máquina)',
  '抬tái': 'Levantar',
  '态度tàidù': 'Actitud',
  '抬头táitóu': 'Levantar cabeza',
  '弹tán': 'Tocar (instrumento)',
  '谈tán': 'Hablar',
  '趟tàng': 'Viaje (ida y vuelta)',
  '躺tǎng': 'Acostarse',
  '汤tāng': 'Sopa',
  '讨论tǎolùn': 'Discutir',
  '讨厌tǎoyàn': 'Odiar',
  '特点tèdiǎn': 'Característica',
  '提tí': 'Llevar',
  '填写tiánxiě': 'Llenar',
  '条件tiáojiàn': 'Condición',
  '提出tíchū': 'Proponer',
  '提到tídào': 'Mencionar',
  '提供tígōng': 'Proporcionar',
  '体检tǐjiǎn': 'Examen médico',
  '停tíng': 'Parar',
  '停车tíngchē': 'Estacionar',
  '停车场tíngchēchǎng': 'Estacionamiento',
  '听力tīnglì': 'Comprensión auditiva',
  '停止tíngzhǐ': 'Detener',
  '听众tīngzhòng': 'Audiencia',
  '提前tíqián': 'Adelantar',
  '体温tǐwēn': 'Temperatura corporal',
  '提醒tíxǐng': 'Recordar',
  '体重tǐzhòng': 'Peso',
  '痛tòng': 'Dolor',
  '桶tǒng': 'Cubo',
  '通tōng': 'Comunicar',
  '通过tōngguò': 'Pasar por',
  '童年tóngnián': 'Infancia',
  '同时tóngshí': 'Al mismo tiempo',
  '同样tóngyàng': 'Mismo',
  '通知tōngzhī': 'Notificar',
  '头痛tóutòng': 'Dolor de cabeza',
  '图tú': 'Mapa',
  '土tǔ': 'Tierra',
  '推tuī': 'Empujar',
  '推迟tuīchí': 'Posponer',
  '推出tuīchū': 'Lanzar',
  '脱tuō': 'Quitar',
  '图片túpiàn': 'Imagen',
  '外出wàichū': 'Salir',
  '外套wàitào': 'Abrigo',
  '晚安wǎnān': 'Buenas noches',
  '晚餐wǎncān': 'Cena',
  '网购wǎnggòu': 'Comprar en línea',
  '往往wǎngwǎng': 'A menudo',
  '网页wǎngyè': 'Página web',
  '网友wǎngyǒu': 'Amigo en línea',
  '网址wǎngzhǐ': 'URL',
  '完全wánquán': 'Completamente',
  '袜子wàzi': 'Calcetines',
  '为wéi': 'Ser',
  '味wèi': 'Sabor',
  '味道wèidào': 'Sabor',
  '卫生wèishēng': 'Higiene',
  '危险wēixiǎn': 'Peligro',
  '闻wén': 'Oler',
  '温度wēndù': 'Temperatura',
  '文件wénjiàn': 'Documento',
  '文章wénzhāng': 'Artículo',
  '文字wénzì': 'Texto',
  '无wú': 'No',
  '午餐wǔcān': 'Almuerzo',
  '无法wúfǎ': 'No poder',
  '误会wùhuì': 'Malentendido',
  '无聊wúliáo': 'Aburrido',
  '无论wúlùn': 'No importa',
  '污染wūrǎn': 'Contaminación',
  '细xì': 'Fino',
  '吸xī': 'Inhalar',
  '下降xiàjiàng': 'Bajar',
  '咸xián': 'Salado',
  '鲜xiān': 'Fresco',
  '项xiàng': 'Ítem',
  '响xiǎng': 'Sonar',
  '香xiāng': 'Fragante',
  '相比xiāngbǐ': 'Comparar',
  '想法xiǎngfǎ': 'Idea',
  '相反xiāngfǎn': 'Opuesto',
  '相互xiānghù': 'Mutuamente',
  '相同xiāngtóng': 'Mismo',
  '详细xiángxì': 'Detallado',
  '鲜花xiānhuā': 'Flores frescas',
  '现金xiànjīn': 'Efectivo',
  '羡慕xiànmù': 'Envidiar',
  '线上xiànshàng': 'En línea',
  '线下xiànxià': 'Fuera de línea',
  '现有xiànyǒu': 'Existente',
  '小吃xiǎochī': 'Snack',
  '效果xiàoguǒ': 'Efecto',
  '笑话xiàohua': 'Chiste',
  '小伙子xiǎohuǒzi': 'Joven',
  '小说xiǎoshuō': 'Novela',
  '消息xiāoxi': 'Noticia',
  '小组xiǎozǔ': 'Grupo',
  '西部xībù': 'Parte oeste',
  '血xiě': 'Sangre',
  '西红柿xīhóngshì': 'Tomate',
  '心xīn': 'Corazón',
  '性xìng': 'Sexo / Naturaleza',
  '醒xǐng': 'Despertar',
  '性别xìngbié': 'Género',
  '兴奋xīngfèn': 'Emocionado',
  '幸福xìngfú': 'Felicidad',
  '性格xìnggé': 'Personalidad',
  '星星xīngxing': 'Estrella',
  '信号xìnhào': 'Señal',
  '辛苦xīnkǔ': 'Trabajoso',
  '心情xīnqíng': 'Estado de ánimo',
  '信息xìnxī': 'Información',
  '信心xìnxīn': 'Confianza',
  '熊xióng': 'Oso',
  '兄弟xiōngdì': 'Hermanos',
  '修xiū': 'Reparar',
  '修理xiūlǐ': 'Reparar',
  '细心xìxīn': 'Cuidadoso',
  '吸引xīyǐn': 'Atraer',
  '许多xǔduō': 'Muchos',
  '学费xuéfèi': 'Matrícula',
  '学院xuéyuàn': 'Colegio',
  '压yā': 'Presionar',
  '牙膏yágāo': 'Pasta de dientes',
  '压力yālì': 'Presión',
  '盐yán': 'Sal',
  '演yǎn': 'Actuar',
  '烟yān': 'Humo',
  '演唱yǎnchàng': 'Cantar',
  '演出yǎnchū': 'Actuación',
  '养成yǎngchéng': 'Formar (hábito)',
  '严格yángé': 'Estricto',
  '阳光yángguāng': 'Sol',
  '样子yàngzi': 'Apariencia',
  '眼镜yǎnjìng': 'Gafas',
  '研究yánjiū': 'Investigar',
  '研究生yánjiūshēng': 'Estudiante de posgrado',
  '眼前yǎnqián': 'Ante los ojos',
  '演员yǎnyuán': 'Actor',
  '严重yánzhòng': 'Grave',
  '邀请yāoqǐng': 'Invitar',
  '要是yàoshi': 'Si',
  '钥匙yàoshi': 'Llave',
  '亚洲Yàzhōu': 'Asia',
  '夜yè': 'Noche',
  '夜晚yèwǎn': 'Noche',
  '也许yěxǔ': 'Quizás',
  '叶子yèzi': 'Hoja',
  '已yǐ': 'Ya',
  '意见yìjiàn': 'Opinión',
  '因此yīncǐ': 'Por lo tanto',
  '以内yǐnèi': 'Dentro de',
  '赢yíng': 'Ganar',
  '赢得yíngdé': 'Ganar',
  '应聘yìngpìn': 'Solicitar empleo',
  '引起yǐnqǐ': 'Causar',
  '印象yìnxiàng': 'Impresión',
  '一切yíqiè': 'Todo',
  '一生yìshēng': 'Toda la vida',
  '艺术yìshù': 'Arte',
  '勇敢yǒnggǎn': 'Valiente',
  '用来yònglái': 'Usar para',
  '用于yòngyú': 'Usar en',
  '永远yǒngyuǎn': 'Para siempre',
  '由yóu': 'Por',
  '油yóu': 'Aceite',
  '优点yōudiǎn': 'Ventaja',
  '友好yǒuhǎo': 'Amigable',
  '幽默yōumò': 'Humor',
  '尤其yóuqí': 'Especialmente',
  '友情yǒuqíng': 'Amistad',
  '有趣yǒuqù': 'Interesante',
  '游玩yóuwán': 'Jugar',
  '有效yǒuxiào': 'Efectivo',
  '优秀yōuxiù': 'Excelente',
  '友谊yǒuyì': 'Amistad',
  '由于yóuyú': 'Debido a',
  '有着yǒuzhe': 'Tener',
  '与yǔ': 'Con',
  '原来yuánlái': 'Original',
  '远离yuǎnlí': 'Alejarse',
  '原谅yuánliàng': 'Perdonar',
  '原因yuányīn': 'Razón',
  '院长yuànzhǎng': 'Decano',
  '院子yuànzi': 'Patio',
  '约yuē': 'Acordar',
  '月饼yuèbing': 'Pastel de luna',
  '阅读yuèdú': 'Leer',
  '月份yuèfèn': 'Mes',
  '约会yuēhuì': 'Cita',
  '语法yǔfǎ': 'Gramática',
  '愉快yúkuài': 'Feliz',
  '云yún': 'Nube',
  '允许yǔnxǔ': 'Permitir',
  '于是yúshì': 'Entonces',
  '预习yùxí': 'Preparar lección',
  '再次zàicì': 'De nuevo',
  '再说zàishuō': 'Además',
  '暂时zànshí': 'Temporal',
  '暂停zàntíng': 'Pausar',
  '早餐zǎocān': 'Desayuno',
  '早晨zǎochen': 'Mañana',
  '杂志zázhì': 'Revista',
  '增加zēngjiā': 'Aumentar',
  '增长zēngzhǎng': 'Crecer',
  '责任zérèn': 'Responsabilidad',
  '着zháo': 'Tocar',
  '着火zháohuǒ': 'Incendiarse',
  '招聘zhāopìn': 'Reclutar',
  '者zhě': 'Persona',
  '证zhèng': 'Certificado',
  '整zhěng': 'Entero',
  '正常zhèngcháng': 'Normal',
  '整个zhěnggè': 'Completo',
  '正好zhènghǎo': 'Justo',
  '证件zhèngjiàn': 'Documento',
  '整理zhěnglǐ': 'Organizar',
  '证明zhèngmíng': 'Probar',
  '正确zhèngquè': 'Correcto',
  '正式zhèngshì': 'Formal',
  '真正zhēnzhèng': 'Verdadero',
  '值zhí': 'Valer',
  '指zhǐ': 'Señalar',
  '之zhī': 'De (posesivo)',
  '支持zhīchí': 'Apoyar',
  '指出zhǐchū': 'Señalar',
  '值得zhídé': 'Merecer',
  '支付zhīfù': 'Pagar',
  '只好zhǐhǎo': 'No tener más remedio',
  '之后zhīhòu': 'Después de',
  '之间zhījiān': 'Entre',
  '直接zhíjiē': 'Directo',
  '纸巾zhǐjīn': 'Servilleta',
  '质量zhìliàng': 'Calidad',
  '之前zhīqián': 'Antes de',
  '至少zhìshǎo': 'Al menos',
  '知识zhīshi': 'Conocimiento',
  '植物zhíwù': 'Planta',
  '职业zhíyè': 'Profesión',
  '之中zhīzhōng': 'En medio',
  '种zhòng': 'Plantar',
  '重zhòng': 'Pesado',
  '中餐zhōngcān': 'Comida china',
  '重点zhòngdiǎn': 'Punto clave',
  '中年zhōngnián': 'Mediana edad',
  '重视zhòngshì': 'Valorar',
  '周围zhōuwéi': 'Alrededor',
  '祝zhù': 'Desear',
  '赚zhuàn': 'Ganar (dinero)',
  '转zhuǎn': 'Girar',
  '转发zhuǎnfā': 'Reenviar',
  '装zhuāng': 'Instalar',
  '转机zhuǎnjī': 'Transbordo',
  '专门zhuānmén': 'Especialmente',
  '专业zhuānyè': 'Especialidad',
  '祝贺zhùhè': 'Felicitar',
  '著名zhùmíng': 'Famoso',
  '准zhǔn': 'Preciso',
  '准确zhǔnquè': 'Preciso',
  '准时zhǔnshí': 'Puntual',
  '主意zhǔyi': 'Idea',
  '自zì': 'Desde',
  '资料zīliào': 'Materiales',
  '自然zìrán': 'Naturaleza',
  '自习zìxí': 'Estudiar por uno mismo',
  '仔细zǐxì': 'Cuidadoso',
  '自信zìxìn': 'Confianza',
  '自学zìxué': 'Autoaprendizaje',
  '总结zǒngjié': 'Resumir',
  '组zǔ': 'Grupo',
  '租zū': 'Alquilar',
  '最终zuìzhōng': 'Final',
  '尊重zūnzhòng': 'Respetar',
  '座zuò': 'Asiento',
  '做法zuòfǎ': 'Práctica',
  '作家zuòjiā': 'Escritor',
  '做梦zuòmèng': 'Soñar',
  '作品zuòpǐn': 'Obra',
  '作为zuòwéi': 'Como',
  '座位zuòwèi': 'Asiento',
  '作文zuòwén': 'Composición',
  '作用zuòyòng': 'Función',
  '左右zuǒyòu': 'Alrededor',
  '作者zuòzhě': 'Autor',

  // Variantes de formato HSK 1-2
  '点1diǎn': 'Punto / Hora',
  '点2diǎn': 'Tocar',
  '会1huì': 'Saber hacer / Poder',
  '会2huì': 'Reunión',
  '两1liǎng': 'Dos (medida)',
  '两2liǎng': 'Tael (50g)',
  '喂1wèi': 'Hola (teléfono)',
  '别1bié': 'No (imperativo)',
  '打1dǎ': 'Golpear',
  '等1děng': 'Esperar',
  '等2děng': 'Etcétera',
  '过去1guòqù': 'Pasar',
  '过去2guòqù': 'Pasado',
  '花1huā': 'Gastar',
  '花2huā': 'Flor',
  '面1miàn': 'Lado',
  '站1zhàn': 'Estación / Parada',
  '站2zhàn': 'Estar de pie',
  '才1cái': 'Apenas / Solo',
  '该1gāi': 'Deber',
  '可爱kěài': 'Lindo',
  '喜爱xǐài': 'Adorar',
  '乘1chéng': 'Multiplicar / Viajar en',
  '答案dáàn': 'Respuesta',
  '骄傲jiāoào': 'Orgulloso',
  '偶尔ǒuěr': 'Ocasionalmente',
  '然而ránér': 'Sin embargo',
  '省1shěng': 'Provincia',
  '生1shēng': 'Nacer',
  '生2shēng': 'Crudo',
  '晚安wǎnān': 'Buenas noches',
  '为1wéi': 'Ser',
  '线上xiànshàng': 'En línea',
  '之1zhī': 'De (posesivo)',
  '转机1zhuǎnjī': 'Transbordo',
  '作为1zuòwéi': 'Como',
  'kěài': 'Lindo',
  'xǐài': 'Adorar',
  'dáàn': 'Respuesta',
  'jiāoào': 'Orgulloso',
  'ǒuěr': 'Ocasionalmente',
  'ránér': 'Sin embargo',
  'wǎnān': 'Buenas noches',
  'xiàshàng': 'En línea',
  'kě\'ài': 'Lindo',
  'xǐ\'ài': 'Adorar',
  'dá\'àn': 'Respuesta',
  'jiāo\'ào': 'Orgulloso',
  'ǒu\'ěr': 'Ocasionalmente',
  'rán\'ér': 'Sin embargo',
  'wǎn\'ān': 'Buenas noches'
};

function leerVocabularioHSK(archivo) {
  const niveles = new Map([
    [1, []],
    [2, []],
    [3, []],
    [4, []],
  ]);

  const contenido = fs.readFileSync(archivo, 'utf-8');
  const lineas = contenido.split(/\r?\n/);

  for (const linea of lineas) {
    const limpia = linea.trim();
    if (!limpia) continue;

    // El formato puede ser:
    // 1. lineNum sequential hanziPinyin type
    // 2. lineNum sequential hanziNumber pinyin type (cuando hay número después del hanzi)

    const partes = limpia.split(/\s+/);
    if (partes.length < 3) continue;

    const lineNum = parseInt(partes[0]);
    const sequential = parseInt(partes[1]);

    // Intentar detectar si hay pinyin separado
    // Si partes[3] contiene letras latinas (a-z, tonos), es probablemente el pinyin
    let hanziPinyin, type;

    if (partes.length >= 4 && /^[a-zA-Zāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜü]/.test(partes[3])) {
      // Formato: lineNum sequential hanziNumber pinyin type
      // Combinar hanzi+número con pinyin
      hanziPinyin = partes[2] + partes[3];
      type = partes.slice(4).join(' ');
    } else {
      // Formato normal: lineNum sequential hanziPinyin type
      hanziPinyin = partes[2];
      type = partes.slice(3).join(' ');
    }

    // Determinar nivel según el número de línea
    let level;
    if (lineNum <= 300) level = 1;
    else if (lineNum <= 500) level = 2;
    else if (lineNum <= 1000) level = 3;
    else level = 4;

    if (niveles.has(level)) {
      niveles.get(level).push({
        lineNum,
        sequential,
        level,
        hanziPinyin,
        type,
      });
    }
  }

  return niveles;
}

function separarHanziPinyin(hanziPinyin) {
  // El formato puede ser:
  // 1. 爱ài -> hanzi + pinyin
  // 2. 本1 běn -> hanzi + número + espacio + pinyin (necesita parseo especial)

  // Primero intentar separar por caracteres chinos vs no-chinos
  // Los caracteres chinos están en el rango Unicode 一-鿿
  const match = hanziPinyin.match(/^([一-鿿]+)(.*)$/);

  if (match) {
    let hanzi = match[1];
    let resto = match[2];

    // Si el resto empieza con números o paréntesis, buscar la primera letra
    // Ejemplos: "1（4）" -> extraer solo los números/paréntesis, el pinyin vendría después
    const matchPinyin = resto.match(/^[0-9（）\s]*([a-zA-Zāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜüêê]+.*)$/);

    if (matchPinyin) {
      return {
        hanzi: hanzi,
        pinyin: matchPinyin[1].trim(),
      };
    }

    return {
      hanzi: hanzi,
      pinyin: resto.trim(),
    };
  }

  return { hanzi: hanziPinyin, pinyin: '' };
}

function organizarEnLecciones(niveles, palabrasPorLeccion = 10) {
  const resultado = new Map();

  for (const [nivel, palabras] of niveles.entries()) {
    const lecciones = [];
    const numLecciones = Math.ceil(palabras.length / palabrasPorLeccion);

    for (let i = 0; i < numLecciones; i++) {
      const inicio = i * palabrasPorLeccion;
      const fin = Math.min(inicio + palabrasPorLeccion, palabras.length);
      const palabrasLeccion = palabras.slice(inicio, fin);

      const cards = palabrasLeccion.map((palabra) => {
        const { hanzi, pinyin } = separarHanziPinyin(palabra.hanziPinyin);
        const significado = SIGNIFICADOS[palabra.hanziPinyin] || '(Por traducir)';

        return {
          chino: hanzi,
          pinyin: pinyin,
          significado: significado,
        };
      });

      lecciones.push({
        key: `hsk${nivel}_leccion_${i + 1}`,
        label: `HSK ${nivel} - Lección ${i + 1}`,
        cards: cards,
      });
    }

    resultado.set(nivel, lecciones);
  }

  return resultado;
}

function generarCodigoTypeScript(lecciones) {
  let codigo = `// Vocabulario HSK 3.0 organizado por niveles y lecciones
// Generado automáticamente - 10 palabras por lección

import { Book } from './vocabulary';

`;

  // Generar los libros
  codigo += `export const HSK_BOOKS: Book[] = [\n`;

  for (const [nivel, leccionesNivel] of lecciones.entries()) {
    codigo += `  {\n`;
    codigo += `    id: 'hsk${nivel}_v3',\n`;
    codigo += `    label: 'HSK ${nivel} v3.0 (${leccionesNivel.length} lecciones)',\n`;
    codigo += `    lessons: [\n`;

    for (const leccion of leccionesNivel) {
      codigo += `      {\n`;
      codigo += `        key: '${leccion.key}',\n`;
      codigo += `        label: '${leccion.label}',\n`;
      codigo += `        cards: [\n`;

      for (const card of leccion.cards) {
        const significadoEscaped = card.significado.replace(/'/g, "\\'");
        const pinyinEscaped = card.pinyin.replace(/'/g, "\\'");
        codigo += `          { chino: '${card.chino}', pinyin: '${pinyinEscaped}', significado: '${significadoEscaped}' },\n`;
      }

      codigo += `        ],\n`;
      codigo += `      },\n`;
    }

    codigo += `    ],\n`;
    codigo += `  },\n`;
  }

  codigo += `];\n`;

  return codigo;
}

function main() {
  const archivoEntrada = path.join(__dirname, 'public', 'HSK1-9.txt');
  const archivoSalida = path.join(__dirname, 'src', 'app', 'data', 'hsk-vocabulary.ts');

  console.log('📖 Leyendo vocabulario HSK...');
  const niveles = leerVocabularioHSK(archivoEntrada);

  console.log('\n📊 Resumen por nivel:');
  let totalPalabras = 0;
  let totalLecciones = 0;

  for (const [nivel, palabras] of niveles.entries()) {
    const numLecciones = Math.ceil(palabras.length / 10);
    console.log(`  HSK ${nivel}: ${palabras.length} palabras = ${numLecciones} lecciones`);
    totalPalabras += palabras.length;
    totalLecciones += numLecciones;
  }

  console.log(`\n  TOTAL: ${totalPalabras} palabras = ${totalLecciones} lecciones\n`);

  console.log('🔄 Organizando en lecciones de 10 palabras...');
  const lecciones = organizarEnLecciones(niveles, 10);

  console.log('✍️  Generando código TypeScript...');
  const codigo = generarCodigoTypeScript(lecciones);

  console.log(`💾 Guardando en ${archivoSalida}...`);
  fs.writeFileSync(archivoSalida, codigo, 'utf-8');

  console.log('\n✅ Archivo generado exitosamente!');
  console.log('\n⚠️  NOTA: Las palabras están marcadas como "(Por traducir)"');
  console.log('   Necesitas agregar los significados en español.\n');

  // Mostrar estadísticas de palabras sin traducir
  let sinTraducir = 0;
  for (const [_, leccionesNivel] of lecciones.entries()) {
    for (const leccion of leccionesNivel) {
      for (const card of leccion.cards) {
        if (card.significado === '(Por traducir)') {
          sinTraducir++;
        }
      }
    }
  }

  console.log(`📝 Palabras sin traducir: ${sinTraducir} de ${totalPalabras}\n`);
}

main();
